In [4]:
def A(arr):
    arr[0] = 8
def B(arr):
    arr[1] = 8
a = [1,2,3]
A([x for x in a])
B([x for x in a])
print(a)

[1, 2, 3]


In [2]:
import torch
a = torch.tensor([[
    0,1,2,3,4,5,6,7
]])
b = a[:,:-1]
c = a[::]
print(a)
print(b)
print(c)

tensor([[0, 1, 2, 3, 4, 5, 6, 7]])
tensor([[0, 1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3, 4, 5, 6, 7]])
